### ISSUE TITLE
Баги

### ISSUE THREAD

**Issue by yuchiko** [antonMihalev/site-tajam#1]
- в адаптиве для телефона сайт летит
- Иконка в секции видео не центрирована и странно смотрится, очень много пустого места
- не забывай про transition на ховерах, а то резко смотрится
- плавности при скролле не будет? 
- с meta и link как и в j-wood, смотри в те issues
- постарайся избегать `<br>Please<br>` новую строку ты мог сделать и свойством дисплей блок
- бургер выглядит как белый квадрат ?
- `<cite>` нужно использовать для указания автора цитаты, но не для должности этого автора
- аlt много где указан абы как
- `.social_list li:nth-child(2)` неет! А, если скажут поменять местами, убрать соц сеть? Никогда так не делай
- jquery первым
```
<script src="js/preloader.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
```
- не надо разных регистров в названиях классов `buttonLG`
-

**Comment by antonMihalev** [comment]
1.Адаптив насколько вижу переделал
2.Иконка в секции видео центрирована уже
3.Сделал транзишн для ссылок и кнопок
4.Плавность при скролле есть
5.Мета перенес как и в j-wood
6.Заменил <br> на display:block
7.Бургер изменил
8.Заменил <cite>с позицией  на <p>

**Comment by antonMihalev** [comment]
9.Альты поуказывал и поизменял где нашел
10.Заменил  последовательные классы соц сетей и дал каждой <li> свой класс соответствующий соц-сети
11.jquary поставил перед скриптами 
12.заменил .buttonLG - на .button_large
